CREATE PROCEDURE SYSPROC.ACCOUNT_DETAILS (
    IN ACCOUNT_NUMBER CHAR(16),
    OUT BALANCE_OUT DECIMAL(15,2),
    OUT CURRENCY_OUT CHAR(3)
)
LANGUAGE SQL
BEGIN
    SET BALANCE_OUT = 100.00;
    SET CURRENCY_OUT = 'USD';
END;
