CREATE OR REPLACE PACKAGE BILLING_PKG AS
  PROCEDURE CALC_INVOICE_TOTAL(p_order_id IN VARCHAR2, p_total OUT NUMBER);
END BILLING_PKG;
/
CREATE OR REPLACE PACKAGE BODY BILLING_PKG AS
  PROCEDURE CALC_INVOICE_TOTAL(p_order_id IN VARCHAR2, p_total OUT NUMBER) IS
  BEGIN
    p_total := 123.45;
  END;
END BILLING_PKG;
/
