-- Create CUSTOMER table for local/H2 mode
CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME  VARCHAR(100) NOT NULL,
    EMAIL      VARCHAR(200) NOT NULL UNIQUE
);

-- Create CUSTOMER_AUDIT table (used for S3 + Oracle + H2 mode)
CREATE TABLE IF NOT EXISTS CUSTOMER_AUDIT (
    ID IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME  VARCHAR(100) NOT NULL,
    EMAIL      VARCHAR(200) NOT NULL
);
